### ISSUE TITLE
[Enhancement] integrating with plex apps

### ISSUE THREAD

**Issue by bmbowdish** [brandonhudson/CSHMovies#5]
I was thinking that you could click on the movie and it opens that movie in the plex app on Desktop, In Browser, on the mobile app, etc.

**Comment by liam-middlebrook** [comment]
This is something that we're looking into the possibility of. Thanks for taking the time to file an issue for this request.

**Comment by brandonhudson** [comment]
'Quick and Dirty' solution just added:

When you click/tap on the image art, it will open the plex web app on desktop (displays over 768px) and the plex app on mobile (displays under 768px). It DOES NOT open directly to the movie, as that is not possible on mobile (at least publicly talked about), it simply opens the app to make a faster transition. This adds a decent improvement for now.

TODO: 
- Look into custom URL scheme for mobile to open correct server and movie
- Look into customer URL scheme for plex web app 
- Do routing based on device rather than on display width
